### PR TITLE
Add FreshONES.net

### PR DESCRIPTION
**Pull request by gaia**

### CODE REVIEW

**Comment by lijiang2087** [comment]
hey you need to add to validator folder, there's a conflict so can't merge this @gaia

**Comment by gaia** [comment]
which folder?  i see nothing about a folder in the instructions

**Comment by gaia** [comment]
but if you look at my PR's version of list.json, you will see it is properly formatted
https://github.com/gaia/validator-logos/blob/master/list.json

the problem is whomever came after me did not open bracket
image

https://github.com/harmony-one/validator-logos/pull/150/conflicts

**Comment by gaia** [comment]
I'd appreciate this being resolved before the next epoch. thanks!

**Comment by gaia** [comment]
Hi @NiteeshHarmony. Why isn't the logo showing up in the staking dashboard yet?

**Comment by gaia** [comment]
Hi @lijiang2087, why isn't the logo showing up in the staking dashboard yet?

**Pull request merged**
