### PR TITLE
validator "teahouse" logo

### PR DESCRIPTION
**Pull request by teemaja**

### CODE REVIEW

**Comment by mikedoan** [comment]
can you make it jpg?

**Comment by teemaja** [comment]
Yes, I made it now jpg, I hope this works, this "commenting" is new thing for me.
one1k9577lnpfx7z76zslc6r8gdmsp5kqgpll7cpk9

**Comment by teemaja** [comment]
Now with one address in name.

one1k9577lnpfx7z76zslc6r8gdmsp5kqgpll7cpk9.jpg

**Comment by mikedoan** [comment]
@teemaja but i did not see it changed in this PR - you need to make another commit

**Comment by teemaja** [comment]
Ok, I try.

**Pull request merged**
