### PR TITLE
Upload logo for Moonstake validator

### PR DESCRIPTION
**Pull request by congle-ibl**

### CODE REVIEW

**Comment by NiteeshHarmony** [comment]
Screen Shot 2020-07-29 at 2 55 41 PM
Getting a merge conflict.

**Comment by congle-ibl** [comment]
Hi @NiteeshHarmony 

I have just resolved the merge conflict, please help to take a look, thank you so much.

Best Regards,
Lucas

**Comment by congle-engineer** [comment]
Hi all, 

Please help to merge this branch, thank you so much.

**Comment by NiteeshHarmony** [comment]
Hey guys, still says conflicting files.

**Pull request closed without merging**
